states = [
    "Alabama",
"Alaska",
"American Samoa",
"Arizona",
"Arkansas",
"California",
"Colorado",
"Connecticut",
"Delaware",
"District of Columbia",
"Florida",
"Georgia",
"Guam",
"Hawaii",
"Idaho",
"Illinois",
"Indiana",
"Iowa",
"Kansas",
"Kentucky",
"Louisiana",
"Maine",
"Maryland",
"Massachusetts",
"Michigan",
"Minnesota",
"Mississippi",
"Missouri",
"Montana",
"Nebraska",
"Nevada",
"New Hampshire",
"New Jersey",
"New Mexico",
"New York",
"North Carolina",
"North Dakota",
"Northern Mariana Islands",
"Ohio",
"Oklahoma",
"Oregon",
"Pennsylvania",
"Puerto Rico",
"Rhode Island",
"South Carolina",
"South Dakota",
"Tennessee",
"Texas",
"United States Minor Outlying Islands",
"Utah",
"Vermont",
"Virgin Islands",
"Virginia",
"Washington",
"West Virginia",
"Wisconsin",
"Wyoming",
]

crime_types = ["Advanced Fee", "Identity Theft", "BEC/EAC", "Investment", "Charity", "Lottery/Sweepstakes/Inheritance", "Civil Matter", "Malware/Scareware/Virus", "Confidence Fraud/Romance", "Misrepresentation", "Corporate Data Breach", "No Lead Value", "Credit Card Fraud", "Non-payment/Non-Delivery", "Crimes Against Children", "Other", "Criminal Forums", "Overpayment", "Denial of Service/TDos", "Personal Data Breach", "Employment", "Phishing/Vishing/Smishing/Pharming", "Extortion", "Ransomware", "Gambling", "Re-shipping", "Government Impersonation", "Real Estate/Rental", "Hacktivist", "Spoofing", "Harassment/Threats of Violence", "Tech Support", "Health Care Related", "Terrorism", "IPR/Copyright and Counterfeit"]
data_types =  ["victim_count", "victim_loss", "subject_count", "subject_loss"]
